kind: pipeline
type: docker
name: blogSsr

steps:
  - name: 生成部署配置
    image: busybox
    commands:
      - echo $DRONE_COMMIT
      - '[ -n "$DRONE_COMMIT" ] && (
          sed -i "s/TAG/${DRONE_COMMIT_SHA}/g" deployment.yml;
          sed -i "s/APP_NAME/blog-ssr/g" deployment.yml;
          sed -i "s/IMAGE_NAME/blog-ssr/g" deployment.yml;
          sed -i "s/DOMAIN_NAME/ssr/g" deployment.yml;
          sed -i "s/NAMESPACE/blog-project/g" deployment.yml
        )'
      - sed -i "s/ENV_BUILD_DATE/$(date +'%Y-%m-%y %T')/g" deployment.yml
      - cat deployment.yml

  - name: 打包构建
    image: docker.carrotwu.com/blog/blog-ssr-node-modules
    commands:
      - ls -la
      - mv /node_modules node_modules
      - ls -la

  - name: 生成镜像
    #name: 打包构建生成镜像
    image: plugins/docker
    settings:
      debug: true
      dockerfile: Dockerfile # 使用 Dockerfile 的名字
      repo: docker.carrotwu.com/blog/blog-ssr
      mirror: https://docker.mirrors.ustc.edu.cn/
      registry: docker.carrotwu.com
      tag: ${DRONE_COMMIT_SHA}
      username:
        from_secret: dockerUserName
      password:
        from_secret: dockerPassword

  - name: deployment
    image: sinlead/drone-kubectl
    settings:
      kubernetes_server: https://172.17.16.12:6443            # k8s 集群地址
      namespace: blog-project
      kubernetes_token:
        from_secret: k8sToken
      kubernetes_cert:
        from_secret: k8sCe
      deployment: blog-ssr                    # 容器名
      repo: docker.carrotwu.com/blog/blog-ssr
      container: blog-ssr
      tag:
        - ${DRONE_COMMIT_SHA}
      # 需要被部署的镜像 TAG
    commands:
      - cat deployment.yml
      - kubectl apply  -f deployment.yml

trigger:
  branch:
    - master
